export const DEFAULT_CATEGORIES = [
  {
    name: "Salary",
    type: "INCOME",
    icon: "briefcase",
    color: "emerald",
    displayOrder: 1,
  },
  {
    name: "Freelance",
    type: "INCOME",
    icon: "laptop",
    color: "blue",
    displayOrder: 2,
  },
  {
    name: "Investment",
    type: "INCOME",
    icon: "trending-up",
    color: "purple",
    displayOrder: 3,
  },
  {
    name: "Refund",
    type: "INCOME",
    icon: "rotate-ccw",
    color: "cyan",
    displayOrder: 4,
  },

  {
    name: "Food",
    type: "EXPENSE",
    icon: "utensils",
    color: "orange",
    displayOrder: 10,
  },
  {
    name: "Transport",
    type: "EXPENSE",
    icon: "car",
    color: "blue",
    displayOrder: 11,
  },
  {
    name: "Shopping",
    type: "EXPENSE",
    icon: "shopping-bag",
    color: "pink",
    displayOrder: 12,
  },
  {
    name: "Bills",
    type: "EXPENSE",
    icon: "receipt",
    color: "yellow",
    displayOrder: 13,
  },
  {
    name: "Rent",
    type: "EXPENSE",
    icon: "home",
    color: "red",
    displayOrder: 14,
  },
  {
    name: "Entertainment",
    type: "EXPENSE",
    icon: "film",
    color: "violet",
    displayOrder: 15,
  },
  {
    name: "Healthcare",
    type: "EXPENSE",
    icon: "heart-pulse",
    color: "rose",
    displayOrder: 16,
  },
  {
    name: "Education",
    type: "EXPENSE",
    icon: "graduation-cap",
    color: "indigo",
    displayOrder: 17,
  },
  {
    name: "Investment",
    type: "EXPENSE",
    icon: "trending-up",
    color: "teal",
    displayOrder: 18,
  },
  {
    name: "Other",
    type: "EXPENSE",
    icon: "circle",
    color: "gray",
    displayOrder: 19,
  },
];