import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const read = (name) => fs.readFileSync(path.join(root, name), "utf8");
const activity = read("server/src/services/transactionActivity.service.js");
const transactionRoutes = read("server/src/routes/transaction.routes.js");
const transactionPage = read("client/src/pages/TransactionsPage.jsx");
const transactionService = read("client/src/services/transactionService.js");
const table = read("client/src/components/transactions/TransactionTable.jsx");
const accounts = read("client/src/pages/AccountsPage.jsx");
const investmentPage = read("client/src/pages/InvestmentsPage.jsx");
const quoteService = read("server/src/services/marketData.service.js");
const quoteModel = read("server/src/models/InvestmentInstrument.js");
const quoteUi = read("client/src/utils/quotePresentation.js");
const tradeModal = read("client/src/components/investments/InvestmentTradeModal.jsx");
const csv = read("client/src/utils/exportTransactionsCsv.js");
const dashboard = read("client/src/components/dashboard/CashFlowChart.jsx");

assert(transactionRoutes.includes('router.get("/activity", validate(transactionQuerySchema), getTransactionActivity)'), "Activity endpoint must be protected and validated");
assert(activity.includes("{ $unionWith:") && activity.includes("InvestmentTrade.collection.name"), "Activity feed must combine ledgers server-side");
assert(activity.includes("{ user }") && activity.includes("trade.account = account"), "Activity trade search must be user-owned and account-filtered");
assert(activity.includes('recordKind: "INVESTMENT_TRADE"') && !activity.includes("InvestmentTrade.create"), "Investment activity must be read-only without duplicate ledger writes");
assert(activity.includes('ordinary._id = { $exists: false }') && activity.includes('trade._id = { $exists: false }'), "Investment and ordinary filters must remain mutually exclusive");
assert(transactionService.includes('api.get("/transactions/activity"') && transactionPage.includes("getTransactionsForExport"), "Table and CSV must use unified activity feed");
assert(table.includes('disabled={isTrade}') && table.includes('recordKind === "INVESTMENT_TRADE"'), "Investment trades must not enter ordinary transaction edit/bulk-delete paths");
assert(csv.includes('"Net cash movement"') && csv.includes('"Realised P&L"') && csv.includes("neutralizeSpreadsheetFormula"), "CSV must retain investment-specific columns and spreadsheet safety");
assert(accounts.includes('navigate(`/transactions?accountId='), "Account history shortcut must preserve accountId in the URL");
assert(transactionPage.includes("getAccountDirectory({ includeArchived: true })"), "Account history filtering must also support archived accounts");
assert(investmentPage.includes('View investment accounts') && investmentPage.includes('Create another account'), "Investment button must expose view/create actions");
assert(investmentPage.includes('location.state?.tab'), "Trade-row links must open the investment activity tab");
assert(investmentPage.includes('setAccountActions("list")') && investmentPage.includes('encodeURIComponent(account._id)'), "Existing investment accounts need a directly accessible history");
assert(quoteModel.includes("quoteFetchedAt") && quoteModel.includes("lastTradeAt"), "Quote snapshot fetch and actual trade timestamps must be distinct");
assert(quoteService.includes('last_trade_time') && quoteService.includes('/v2/market/status/'), "Upstox exchange status and last-trade time must come from server-only provider calls");
assert(quoteService.includes("exchangeStatusCache") && quoteService.includes("QUOTE_CACHE_MS"), "Market requests must be cached");
assert(quoteUi.includes('exchangeStatus === "OPEN"') && quoteUi.includes('exchangeStatus === "CLOSED"') && quoteUi.includes("CACHED PRICE"), "UI must not equate polling frequency with live trade prices");
assert(tradeModal.includes("quoteInfo.label") && tradeModal.includes("actual execution price") && tradeModal.includes("priceEdited.current"), "Trade form must show quote provenance while preserving manually entered execution price");
assert(dashboard.includes("expenseFlow: -expense") && dashboard.includes("var(--ft-copper-bright)") && dashboard.includes("renderHoverDot"), "Dashboard chart language must be preserved for future investment visualizations");
console.log("FinTrack v2 Phase 6.1 structural regression tests passed.");
